###

GET http://localhost:3000/

###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/673896091f604a2783ce6387


###

GET http://localhost:3000/posts/by-sender?sender=Yonatan

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "sender": "Yonatan",
    "title": "My second post",
    "content": "This is my second post"
}

###

PUT http://localhost:3000/posts/673896091f604a2783ce6387
Content-Type: application/json

{
    "sender": "Yonatan",
    "title": "Updated post title",
    "content": "This is the updated content"
}
